# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='task_done',
            new_name='tarea_done',
        ),
    ]
